version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/personal-crm-backend/
hooks:
  ApplicationStop:
   - location: purge.sh
     timeout: 300
     runas: root
  AfterInstall:
   - location: setup.sh
     timeout: 2400
     runas: root
  ApplicationStart:
   - location: run.sh
     timeout: 1200
     runas: root
  ValidateService:
   - location: validate.sh
     timeout: 300
     runas: root