version: '3.8'
services:
  db:
    container_name: mysql-db
    image: mysql:8.0
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    volumes:
      - ./db/mysql/init.sql:/data/application/init.sql
    expose:
      # Opens port 3306 on the container
      - 3306
  backend-service:
    container_name: backend-service
    depends_on:
    - db
    build:
      context: ./backend-service
    restart: always
    environment:
      DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ENV: ${ENV}
    ports:
      - "80:8080"
    healthcheck:
      test: "exit 0"
