version: '3.8'
services:
  backend-service:
    container_name: backend-service
    build:
      context: backend-service
    restart: always
    ports:
      - 80:8080
    environment:
      TEST: test
    healthcheck:
      test: "exit 0"
  db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'personal-crm-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    expose:
      # Opens port 3306 on the container
      - 3306