version: '3.8'
services:
  backend-service:
    container_name: backend-service
    build:
      context: ./backend-service
    restart: always
    environment:
      DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ENV: ${ENV}
    ports:
      - "80:8080"
    healthcheck:
      test: "exit 0"
