-- MySQL Script generated by MySQL Workbench
-- Tue Aug 31 18:22:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts` (
  `AccountID` INT NOT NULL,
  `RoleID` INT NOT NULL,
  `AccountName` VARCHAR(45) NOT NULL,
  `AccountDOB` DATE NOT NULL,
  `AccountCreation` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`AccountID`),
  UNIQUE INDEX `AccountID_UNIQUE` (`AccountID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chats` (
  `ChatID` INT NOT NULL,
  `ChatCreation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ChatID`),
  UNIQUE INDEX `ChatID_UNIQUE` (`ChatID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Messages` (
  `MessageID` INT NOT NULL,
  `ChatID` INT NOT NULL,
  `AccountID` INT NOT NULL,
  `MessageTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `MessageText` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`MessageID`, `ChatID`),
  INDEX `fk_Messages_Chat1_idx` (`ChatID` ASC) VISIBLE,
  INDEX `fk_Messages_Accounts1_idx` (`AccountID` ASC) VISIBLE,
  CONSTRAINT `fk_Messages_Chat1`
    FOREIGN KEY (`ChatID`)
    REFERENCES `mydb`.`Chats` (`ChatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Accounts1`
    FOREIGN KEY (`AccountID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tasks` (
  `TaskID` INT NOT NULL,
  `AccountID` INT NOT NULL,
  `TaskName` VARCHAR(45) NOT NULL,
  `TaskDeadline` DATETIME NULL,
  `TaskPriority` INT NULL,
  PRIMARY KEY (`TaskID`, `AccountID`),
  INDEX `fk_Tasks_Accounts1_idx` (`AccountID` ASC) VISIBLE,
  CONSTRAINT `fk_Tasks_Accounts1`
    FOREIGN KEY (`AccountID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TaskNotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TaskNotes` (
  `TaskID` INT NOT NULL,
  `TaskNoteID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TaskID`, `TaskNoteID`),
  CONSTRAINT `fk_Notes_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb`.`Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Meetings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Meetings` (
  `MeetingID` INT NOT NULL,
  `MeetingName` VARCHAR(45) NOT NULL,
  `MeetingDescription` VARCHAR(100) NULL,
  `MeetingCreatorID` INT NOT NULL,
  `MeetingStart` DATETIME NOT NULL,
  `MeetingEnd` DATETIME NOT NULL,
  UNIQUE INDEX `EventID_UNIQUE` (`MeetingID` ASC) VISIBLE,
  PRIMARY KEY (`MeetingID`),
  INDEX `fk_Meetings_Accounts1_idx` (`MeetingCreatorID` ASC) VISIBLE,
  CONSTRAINT `fk_Meetings_Accounts1`
    FOREIGN KEY (`MeetingCreatorID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AccountLoginDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AccountLoginDetails` (
  `AccountID` INT NOT NULL,
  `AccountUsername` VARCHAR(45) NOT NULL,
  `AccountPassword` VARCHAR(45) NOT NULL,
  INDEX `fk_AccountLogin_Accounts_idx` (`AccountID` ASC) VISIBLE,
  PRIMARY KEY (`AccountID`),
  UNIQUE INDEX `AccountID_UNIQUE` (`AccountID` ASC) VISIBLE,
  UNIQUE INDEX `AccountUsername_UNIQUE` (`AccountUsername` ASC) VISIBLE,
  CONSTRAINT `fk_AccountLogin_Accounts`
    FOREIGN KEY (`AccountID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account_Contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account_Contacts` (
  `AccountID` INT NOT NULL,
  `ContactID` INT NOT NULL,
  `ContactCreatedOn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AccountID`, `ContactID`),
  INDEX `fk_Account_Contacts_Accounts2_idx` (`ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Contacts_Accounts1`
    FOREIGN KEY (`AccountID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Contacts_Accounts2`
    FOREIGN KEY (`ContactID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account_Meetings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account_Meetings` (
  `AccountID` INT NOT NULL,
  `MeetingID` INT NOT NULL,
  PRIMARY KEY (`AccountID`, `MeetingID`),
  INDEX `fk_Accounts_has_Event_Event1_idx` (`MeetingID` ASC) VISIBLE,
  INDEX `fk_Accounts_has_Event_Accounts1_idx` (`AccountID` ASC) VISIBLE,
  CONSTRAINT `fk_Accounts_has_Event_Accounts1`
    FOREIGN KEY (`AccountID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Accounts_has_Event_Event1`
    FOREIGN KEY (`MeetingID`)
    REFERENCES `mydb`.`Meetings` (`MeetingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PublicHolidays`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PublicHolidays` (
  `PublicHolidayID` INT NOT NULL,
  `PublicHolidayName` VARCHAR(45) NOT NULL,
  `PublicHolidayDesc` VARCHAR(100) NULL,
  `PublicHolidayStart` DATETIME NOT NULL,
  `PublicHolidayEnd` DATETIME NOT NULL,
  PRIMARY KEY (`PublicHolidayID`),
  UNIQUE INDEX `PublicHolidayID_UNIQUE` (`PublicHolidayID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accounts_Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accounts_Chats` (
  `AccountID` INT NOT NULL,
  `ChatID` INT NOT NULL,
  PRIMARY KEY (`AccountID`, `ChatID`),
  INDEX `fk_Chat_has_Accounts_Accounts1_idx` (`AccountID` ASC) VISIBLE,
  INDEX `fk_Chat_has_Accounts_Chat1_idx` (`ChatID` ASC) VISIBLE,
  CONSTRAINT `fk_Chat_has_Accounts_Chat1`
    FOREIGN KEY (`ChatID`)
    REFERENCES `mydb`.`Chats` (`ChatID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_has_Accounts_Accounts1`
    FOREIGN KEY (`AccountID`)
    REFERENCES `mydb`.`Accounts` (`AccountID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account_Contacts_Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Account_Contacts_Tasks` (
  `TaskID` INT NOT NULL,
  `ContactID` INT NOT NULL,
  PRIMARY KEY (`TaskID`, `ContactID`),
  INDEX `fk_Account_Contacts_has_Tasks_Tasks1_idx` (`TaskID` ASC) VISIBLE,
  INDEX `fk_Account_Contacts_has_Tasks_Account_Contacts1_idx` (`ContactID` ASC) VISIBLE,
  CONSTRAINT `fk_Account_Contacts_has_Tasks_Account_Contacts1`
    FOREIGN KEY (`ContactID`)
    REFERENCES `mydb`.`Account_Contacts` (`ContactID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Contacts_has_Tasks_Tasks1`
    FOREIGN KEY (`TaskID`)
    REFERENCES `mydb`.`Tasks` (`TaskID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
