#
# Build stage
#
FROM maven:3.6.0-jdk-11-slim AS build
RUN mvn -f backend-service-app/pom.xml clean package

#
# Package stage
#
FROM openjdk:11-jre-slim
COPY --from=build backend-service-app/target/*.jar backend-service-app-app.jar
ENTRYPOINT ["java","-jar","backend-service-app-app.jar"]