name: CI Pipeline for pull request into development branch
on:
  pull_request:
    branches: [ dev ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Build Application and Run unit Test
        run: docker-compose --env-file config/dev.env up -d
